# - belongs to a question
# * +label+ the object to display (string)
# * +code+ a code for statistical question/choice correlation (string)´
# * +url+ the image matching this choice (string)
class Choice < ActiveRecord::Base

  belongs_to :question  
  belongs_to :author, :class_name => "User", :foreign_key => "author_id"
  has_many :product_filters, :dependent => :destroy
  has_many :tips, :foreign_key => "choice_id", :dependent => :destroy # tips are generated by applying choices
  
  # image associated with this choice
  acts_as_fleximage do
    image_directory 'uploaded_photos/choice'
    require_image false
    default_image_path "public/images/default/default_choice.png" 
  end
  
end

# one choice, x recommendations
class ChoiceSimple < Choice
  
end

class ChoiceOnProduct < Choice

  belongs_to :product
  
end


class ChoiceOnFeatureValue < Choice

  belongs_to :feature_value
  
end

class ChoiceOnFeature < Choice

  belongs_to :feature
  
end

class ChoiceOnFilter < Choice

  belongs_to :feature
  
end

class ChoiceOnTip < Choice

  belongs_to :feature
  belongs_to :product
  belongs_to :feature_value
  
end
