# This file has been generated by the resful authentification plugin

class MainMailer < ActionMailer::Base
  
  def get_domain_name() "wikismo.com" end
  
  def signup_notification(user)
    setup_email(user)
    @subject    += 'Your account has been activated!'
    @body[:url]  = "http://#{get_domain_name}/"  
  end
  
  
  # -------------------------------------------------------------------------
  # BEGIN Methods added by FPA
  # -------------------------------------------------------------------------
  
  def new_password(user, new_password)
    setup_email(user)
    @subject    += 'This is your new password'
    @body[:url]  = "http://#{get_domain_name}/login" 
    @body[:new_password] = new_password
  end
  
  # -------------------------------------------------------------------------
  # END Methods added by FPA
  # -------------------------------------------------------------------------
  
  protected
    def setup_email(user)
      @recipients  = "#{user.name} <#{user.email}>"
      @from        = "info@pikizi.com"
      @subject     = "Pikizi: "
      @sent_on     = Time.now
      @body[:user] = user
    end
    
end


