# A Tip, is a link between a question's possible choice and 
# a recommended product. (generated by a filter)
class Tip < ActiveRecord::Base  
  
  belongs_to :product
  belongs_to :choice
  
  # act as state machine ee rails.aizatto.com/category/plugins/acts_as_state_machine
  #
  acts_as_state_machine :initial => :draft

  state :draft
  state :submitted
  state :reviewed_ok
  state :reviewed_ko
  state :published
  state :trashed
    
  event :submit do transitions(:from => :draft, :to => :submitted) end

  event :review_ok do transitions(:from => :submitted, :to => :reviewed_ok) end
  event :review_ko do transitions(:from => :submitted, :to => :reviewed_ko) end
  event :publish do transitions(:from => :reviewed_ok, :to => :published); transitions(:from => :reviewed_ko, :to => :trashed) end
  event :trash do transitions(:from => [:draft, :submitted, :reviewed_ok, :reviewed_ko, :published], :to => :trashed) end
  event :reset do transitions(:from => [:reviewed_ko, :reviewed_ok, :published], :to => :submitted) end
      
  
end







